inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
Metrics:
  Enabled: false
Style/Semicolon:
  AllowAsExpressionSeparator: true
Style/Documentation:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/NumericPredicate: # ruby 1.8/1.9 do not have positive?/negative?
  EnforcedStyle: comparison

# Disable these until we know what to do with them
Style/PredicateName: # this creates breaking changes in the API
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/WhenThen:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/BlockComments:
  Exclude:
    - benchmarks/*.rb
Style/CaseEquality:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/AlignParameters:
  Enabled: false # does not work correctly with subsequent block
Style/AlignArray:
  Enabled: false # does not support indentation
Style/AlignHash:
  Enabled: false # does not support indentation
Style/GlobalVars:
  Exclude:
    - benchmarks/**/*.rb
    - spec/**/*.rb
